# run: conda env create --file environment.yml --prefix ./env
name: lateral_signaling

dependencies:
  - python=3.9.*
  - numpy=1.19.*
  - pandas=1.*
  - scipy=1.7.*
  - scikit-image
  - numba
  - dask=2021.*
  - colorcet
  - holoviews=1.*
  - matplotlib=3.4.*
  - seaborn=0.*
  - h5py=3.*
  - conda-forge::tqdm=4.*
  - conda-forge::openpiv=0.*
  - conda-forge::imageio-ffmpeg
  - conda-forge::firefox
  - conda-forge::geckodriver
  - conda-forge::nodejs
  - conda-forge::jupyterlab
  - conda-forge::ipympl
  - pip
  - pip:
    - sacred
    - psutil
    # - bebi103==0.1.8
    - matplotlib-scalebar==0.*
    - statannotations
    - ipywidgets
    - blackcellmagic

variables:
  LSIG_DATA_DIR: "../data"
  LSIG_ANALYSIS_DIR: "../data/analysis"
  LSIG_SIMULATION_DIR: "../data/simulations"
  LSIG_PLOTTING_DIR: "../plots"
  LSIG_TEMPPLOTTING_DIR: "../plots/tmp"