# run: conda env create --file environment.yml
name: lateral_signaling

dependencies:
  - python=3.9.*
  - numpy=1.19.*
  - pandas=1.*
  - scipy=1.7.*
  - numba
  - colorcet
  - holoviews=1.*
  - matplotlib=3.4.*
  - conda-forge::tqdm=4.*
  - conda-forge::ffmpeg
#  - conda-forge::ipywidgets
  - conda-forge::shapely=1.*
  - conda-forge::descartes=1.*
  - pip
  - pip:
    - sacred
    - matplotlib-scalebar==0.*
    - cmocean
    - ipywidgets
    - blackcellmagic
