#!/bin/bash

set -ex

mkdir lateral_signaling/sacred
mkdir plots
mkdir plots/tmp
mkdir data

## Download data sets

# From Google Drive
# pip install --no-input gdown
# gdown 11YUNGWajpYoAeQphOeWnuQzNesV17XMH -O data.tar.gz


# From CaltechDATA repository
LSIG_DOI='q8n10-tsk03'
wget \
    --output-document data.tar.gz \
    --user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
    "https://data.caltech.edu/records/$LSIG_DOI/files/2022-10-31_data_minimal.tar.gz?download=1"

tar xf data.tar.gz --directory=data
rm data.tar.gz
