#!/bin/bash

set -ex

mkdir lateral_signaling/sacred
mkdir plots
mkdir plots/tmp
mkdir data

pip install --no-input gdown
gdown 11YUNGWajpYoAeQphOeWnuQzNesV17XMH -O data.tar.gz
tar xf data.tar.gz --directory=data
rm data.tar.gz
