#!/bin/bash

set -ex

pip install --no-input gdown
gdown 1L2CRS9cyrWNCZ68SQhSMQLdt9_J8544g -O data.tar.gz
tar xf data.tar.gz --directory=./data
rm data.tar.gz
mkdir lateral_signaling/sacred
mkdir plots
mkdir plots/tmp
